#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
# dir="`git rev-parse --git-dir`"
dir="."
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  # while read file; do # remove broken symlinks
  #   if [ -e "$file" ]; then
  #     echo "$file"
  #   fi
  # done | \
  ctags --links=no --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql --fields=+zK
# -L - read filenames from stdin
# -f  output file
# --languages=-javascript don't generate tags for javascript or sql
mv "$dir/$$.tags" "$dir/tags"
