font-family = "Cascadia Mono NF"
font-feature = ss19
font-feature = ss20

command = /opt/homebrew/bin/zsh --login --interactive

macos-option-as-alt = left
window-inherit-working-directory = false

theme = "Builtin Tango Dark"
keybind = ctrl+[=text:\x1b

link-previews = true
undo-timeout = 5m

window-inherit-working-directory = false
tab-inherit-working-directory = true
split-inherit-working-directory = true

# custom-shader = ~/.config/ghostty/shaders/animated-gradient-shader.glsl
# custom-shader = ~/.config/ghostty/shaders/bettercrt.glsl
# custom-shader = ~/.config/ghostty/shaders/bloom.glsl
# custom-shader = ~/.config/ghostty/shaders/cineShader-Lava.glsl
# custom-shader = ~/.config/ghostty/shaders/crt.glsl
# custom-shader = ~/.config/ghostty/shaders/cubes.glsl
custom-shader = ~/.config/ghostty/shaders/cursor_blaze.glsl
# custom-shader = ~/.config/ghostty/shaders/dither.glsl
# custom-shader = ~/.config/ghostty/shaders/drunkard.glsl
# custom-shader = ~/.config/ghostty/shaders/fireworks-rockets.glsl
# custom-shader = ~/.config/ghostty/shaders/fireworks.glsl
# custom-shader = ~/.config/ghostty/shaders/galaxy.glsl
# custom-shader = ~/.config/ghostty/shaders/gears-and-belts.glsl
# custom-shader = ~/.config/ghostty/shaders/glitchy.glsl
# custom-shader = ~/.config/ghostty/shaders/glow-rgbsplit-twitchy.glsl
# custom-shader = ~/.config/ghostty/shaders/gradient-background.glsl
# custom-shader = ~/.config/ghostty/shaders/in-game-crt-cursor.glsl
# custom-shader = ~/.config/ghostty/shaders/in-game-crt.glsl
# custom-shader = ~/.config/ghostty/shaders/inside-the-matrix.glsl
# custom-shader = ~/.config/ghostty/shaders/just-snow.glsl
# custom-shader = ~/.config/ghostty/shaders/matrix-hallway.glsl
# custom-shader = ~/.config/ghostty/shaders/mnoise.glsl
# custom-shader = ~/.config/ghostty/shaders/negative.glsl
# custom-shader = ~/.config/ghostty/shaders/retro-terminal.glsl
# custom-shader = ~/.config/ghostty/shaders/sin-interference.glsl
# custom-shader = ~/.config/ghostty/shaders/smoke-and-ghost.glsl
# custom-shader = ~/.config/ghostty/shaders/sparks-from-fire.glsl
# custom-shader = ~/.config/ghostty/shaders/spotlight.glsl
# custom-shader = ~/.config/ghostty/shaders/starfield-colors.glsl
# custom-shader = ~/.config/ghostty/shaders/starfield.glsl
# custom-shader = ~/.config/ghostty/shaders/tft.glsl
# custom-shader = ~/.config/ghostty/shaders/underwater.glsl
# custom-shader = ~/.config/ghostty/shaders/water.glsl

