-- vim.opt_local.autoindent = false -- autoindent noautoindent
-- vim.opt_local.smartindent = false -- smartindent nosmartindent
-- vim.opt_local.cindent = false -- cindent nocindent
-- vim.opt_local.indentexpr = "" -- on after/ftplugin/python.lua
