[[snippets]]
  description = "Show contents of SSL certificate in PEM format"
  command = "openssl x509 -inform pem -in <certfile> -noout -text"
  output = ""

[[snippets]]
  description = "Generate random text"
  command = "base64 /dev/urandom | head -c 100"
  output = ""

[[snippets]]
  description = "Print ssl certificate subject and dates"
  command = "openssl x509 -noout -in <file> -inform der -subject -dates"
  output = ""

[[snippets]]
  description = "Connect to a SSL host and Get the expiration date of the server certificate"
  command = "openssl s_client -servername NAME -connect <server>:<port=443> 2>/dev/null <<< 'Q'| openssl x509 -noout -subject -dates"
  output = ""

[[snippets]]
  description = "List containers in a pod"
  command = "kubectl get pods <podname> -n <namespace>  -o jsonpath='{.spec.containers[*].name}*'"
  output = ""

[[snippets]]
  description = "AWS whoami what IAM user are you using"
  command = "aws sts get-caller-identity"
  output = ""

[[snippets]]
  description = "Delete / remove all stopped docker containers"
  command = "docker rm -v $(docker ps -a -q -f status=exited)"
  output = ""

[[snippets]]
  description = "Generate a random hexadecimal string"
  command = "cat /dev/urandom | LC_ALL=C tr -dc 'a-f0-9' | fold -w 16 | head -n 1"
  output = ""

[[snippets]]
  description = "List all kubernetes deployments in all namespaces"
  command = "kubectl get deployment --all-namespaces"
  output = ""

[[snippets]]
  description = "Kubernetes restart pods in a deployment"
  command = "kubectl -n <namespace> rollout restart deployment <deploymentname>"
  output = ""

[[snippets]]
  description = "List all pods in a deployment"
  command = "kubectl -n <namespace> get pod -l=app=<appname>"
  output = ""

[[snippets]]
  description = "List all tags that contains a certain git commit"
  command = "git tag --contains <commit>"
  output = ""

[[snippets]]
  description = "kubernetes: connect to service via proxy / port-forward"
  command = "kubectl -n <namespace> port-forward service/<service> <localport>:<remoteport>"
  output = ""

[[snippets]]
  description = "Add passphrase / password to private key file pem"
  command = "openssl rsa -aes256 -in <infile> -out <outfile>"
  output = ""

[[snippets]]
  description = "Update stack in AWS CloudFormation"
  command = "aws cloudformation update-stack --stack-name <stackname> --template-body file://<filename>"
  output = ""

[[snippets]]
  description = "pipenv: Find path to virtualenv"
  command = "pipenv --venv"
  output = ""

[[snippets]]
  description = "kubernetes: k8s: List running pods in namespace"
  command = "kubectl -n <namespace> get pods --field-selector=status.phase=Running --watch"
  output = ""

[[snippets]]
  description = "kubernets: k8s: get token for serviceaccount"
  command = "kubectl -n <namespace> get secret $(kubectl -n <namespace> get serviceaccounts <serviceaccount> -o jsonpath='{.secrets[].name}') -o jsonpath='{.data.token}' | base64 -D"
  output = ""

[[snippets]]
  description = "Parse a JWT token"
  command = "jq -R 'split(\".\") | .[1] | @base64d | fromjson' <<< \"$JWT\""
  output = ""

[[snippets]]
  description = "aws: secretsmanager: get secret / retrieve secret value"
  command = "aws secretsmanager get-secret-value --secret-id <secret-id>"
  output = ""

[[snippets]]
  description = "pem: rsa private key: split a single line rsa private ssh key to multi line"
  command = "cat <inputfile> | gsed -e \"s/-----BEGIN RSA PRIVATE KEY-----/&\\n/\" -e \"s/-----END RSA PRIVATE KEY-----/\\n&/\" -e \"s/\\S\\{64,\\}/&\\n/g\" | gsed -e \"s/^\\s*//g\" -e \"/^$/d\""
  output = ""

[[snippets]]
  description = "openssl: Extract certificate chain from ssl server"
  command = "openssl s_client -connect <server>:<port> -showcerts 2>/dev/null <<< 'Q'"
  output = ""

[[snippets]]
  description = "kubernetes: kubectl: Get all logs / Tail log for a deployment"
  command = "kubectl -n <namespace> logs -f deployment/<app-name> --all-containers=true --since=10m"
  output = ""

[[snippets]]
  description = "openssl: Show all certs in a concatenated certificate chain"
  command = "openssl crl2pkcs7 -nocrl -certfile /usr/local/etc/openssl@1.1/cert.pem|openssl pkcs7 -print_certs -noout"
  output = ""

[[snippets]]
  description = "Delete files older than x days"
  command = "find <dir> -type f -mtime +<days> -delete"
  output = ""

[[snippets]]
  description = "kubernetes: find all RoleBindings for a given ServiceAccount"
  command = "kubectl -n <namespace> get rolebindings -o json |  jq -r '.items[] | select(.subjects // [] | .[] | [.kind, .namespace, .name] == [\"ServiceAccount\", \"<namespace>\", \"<serviceaccount>\"]) | .metadata.name'"
  output = ""

[[snippets]]
  description = "kubernetes: find all ClusterRoleBindings for a given ServiceAccount"
  command = "kubectl get clusterrolebindings -o json |  jq -r '.items[] | select(.subjects // [] | .[] | [.kind, .namespace, .name] == [\"ServiceAccount\", \"<namespace>\", \"<serviceaccount>\"]) | .metadata.name'"
  output = ""
