[[snippets]]
  description = "Show contents of SSL certificate in PEM format"
  command = "openssl x509 -inform pem -in <certfile> -noout -text"
  output = ""

[[snippets]]
  description = "Generate random text"
  command = "base64 /dev/urandom | head -c 100"
  output = ""

[[snippets]]
  description = "Print ssl certificate subject and dates"
  command = "openssl x509 -noout -in <file> -inform der -subject -dates"
  output = ""

[[snippets]]
  description = "Connect to a SSL host and Get the expiration date of the server certificate"
  command = "openssl s_client -servername NAME -connect <server>:<port=443> 2>/dev/null <<< 'Q'| openssl x509 -noout -subject -dates"
  output = ""

[[snippets]]
  description = "List containers in a pod"
  command = "kubectl get pods <podname> -n <namespace>  -o jsonpath='{.spec.containers[*].name}*'"
  output = ""

[[snippets]]
  description = "AWS whoami what IAM user are you using"
  command = "aws sts get-caller-identity"
  output = ""

[[snippets]]
  description = "Delete / remove all stopped docker containers"
  command = "docker rm -v $(docker ps -a -q -f status=exited)"
  output = ""

[[snippets]]
  description = "Generate a random hexadecimal string"
  command = "cat /dev/urandom | LC_ALL=C tr -dc 'a-f0-9' | fold -w <size=16> | head -n 1"
  output = ""

[[snippets]]
  description = "List all kubernetes deployments in all namespaces"
  command = "kubectl get deployment --all-namespaces"
  output = ""

[[snippets]]
  description = "Kubernetes restart pods in a deployment"
  command = "kubectl -n <namespace> rollout restart deployment <deploymentname>"
  output = ""

[[snippets]]
  description = "List all pods in a deployment"
  command = "kubectl -n <namespace> get pod -l=app=<appname>"
  output = ""

[[snippets]]
  description = "List all tags that contains a certain git commit"
  command = "git tag --contains <commit>"
  output = ""

[[snippets]]
  description = "kubernetes: connect to service via proxy / port-forward"
  command = "kubectl -n <namespace> port-forward service/<service> <localport>:<remoteport>"
  output = ""

[[snippets]]
  description = "Add passphrase / password to private key file pem"
  command = "openssl rsa -aes256 -in <infile> -out <outfile>"
  output = ""

[[snippets]]
  description = "Update stack in AWS CloudFormation"
  command = "aws cloudformation update-stack --stack-name <stackname> --template-body file://<filename>"
  output = ""

[[snippets]]
  description = "pipenv: Find path to virtualenv"
  command = "pipenv --venv"
  output = ""

[[snippets]]
  description = "kubernetes: k8s: List running pods in namespace"
  command = "kubectl -n <namespace> get pods --field-selector=status.phase=Running --watch"
  output = ""

[[snippets]]
  description = "kubernets: k8s: get token for serviceaccount"
  command = "kubectl -n <namespace> get secret $(kubectl -n <namespace> get serviceaccounts <serviceaccount> -o jsonpath='{.secrets[].name}') -o jsonpath='{.data.token}' | base64 -D"
  output = ""

[[snippets]]
  description = "Parse a JWT token"
  command = "jq -R 'split(\".\") | .[1] | @base64d | fromjson' <<< \"$JWT\""
  output = ""

[[snippets]]
  description = "aws: secretsmanager: get secret / retrieve secret value"
  command = "aws secretsmanager get-secret-value --secret-id <secret-id>"
  output = ""

[[snippets]]
  description = "pem: rsa private key: split a single line rsa private ssh key to multi line"
  command = "cat <inputfile> | gsed -e \"s/-----BEGIN RSA PRIVATE KEY-----/&\\n/\" -e \"s/-----END RSA PRIVATE KEY-----/\\n&/\" -e \"s/\\S\\{64,\\}/&\\n/g\" | gsed -e \"s/^\\s*//g\" -e \"/^$/d\""
  output = ""

[[snippets]]
  description = "openssl: Extract certificate chain from ssl server"
  command = "openssl s_client -connect <server>:<port> -showcerts 2>/dev/null <<< 'Q'"
  output = ""

[[snippets]]
  description = "kubernetes: kubectl: Get all logs / Tail log for a deployment"
  command = "kubectl -n <namespace> logs -f deployment/<app-name> --all-containers=true --since=10m"
  output = ""

[[snippets]]
  description = "openssl: Show all certs in a concatenated certificate chain"
  command = "openssl crl2pkcs7 -nocrl -certfile /usr/local/etc/openssl@1.1/cert.pem|openssl pkcs7 -print_certs -noout"
  output = ""

[[snippets]]
  description = "Delete files older than x days"
  command = "find <dir> -type f -mtime +<days> -delete"
  output = ""

[[snippets]]
  description = "kubernetes: find all RoleBindings for a given ServiceAccount"
  command = "kubectl -n <namespace> get rolebindings -o json |  jq -r '.items[] | select(.subjects // [] | .[] | [.kind, .namespace, .name] == [\"ServiceAccount\", \"<namespace>\", \"<serviceaccount>\"]) | .metadata.name'"
  output = ""

[[snippets]]
  description = "kubernetes: find all ClusterRoleBindings for a given ServiceAccount"
  command = "kubectl get clusterrolebindings -o json |  jq -r '.items[] | select(.subjects // [] | .[] | [.kind, .namespace, .name] == [\"ServiceAccount\", \"<namespace>\", \"<serviceaccount>\"]) | .metadata.name'"
  output = ""

[[snippets]]
  description = "kubernetes: Get CA bundle for kubernetes cluster"
  command = "kubectl get secret $(kubectl get secret -o json | jq -r '.items[] | .metadata.name | select(startswith(\"default-token\"))') -o jsonpath=\"{['data']['ca\\.crt']}\" | base64 --decode"
  output = ""

[[snippets]]
  description = "kubernetes: Get token for a service account"
  command = "kubectl -n kube-system get secret $(kubectl -n kube-system get secret | grep <serviceaccount> | awk '{print $1}') -o jsonpath='{.data.token}'|base64 -D"
  output = ""

[[snippets]]
  description = "kubernetes: Logs for the ALB ingress controller"
  command = "kubectl logs -n kube-system $(kubectl get pod -n kube-system | egrep -o alb-ingress[a-zA-Z0-9-]+)"
  output = ""

[[snippets]]
  description = "netstat: list of open ports / listening ports"
  command = "netstat -ap tcp | grep -i \"listen\""
  output = ""

[[snippets]]
  description = "lsof: list all processes that have open ports  / listening port and show pid"
  command = "sudo lsof -PiTCP -sTCP:LISTEN"
  output = ""

[[snippets]]
  description = "lsof: Show all connections established / listen of all processes"
  command = "lsof -Pn -i4"
  output = ""

[[snippets]]
  description = "openssl: certificate fingerprint as SHA-1"
  command = "openssl x509 -noout -fingerprint -sha1 -inform <pem or der> -in <infile>"
  output = ""

[[snippets]]
  description = "kubernetes: get secret and decode it"
  command = "kubectl -n <namespace> get secret <secretname> -o json | jq -r '<jq path>' | base64 -D"
  output = ""

[[snippets]]
  description = "terraform: Get IP for EC2 instance from the terraform state file"
  command = "cat terraform.tfstate| jq -r '.resources[] | select(.name==\"<resourcename=nifi-test-1>\")| .instances[0].attributes.private_ip'"
  output = ""

[[snippets]]
  description = "kubernetes: kubectl: List pods with the node / nodename they are running on"
  command = "kubectl get pods -o=custom-columns=NAME:.metadata.name,STATUS:.status.phase,NODE:.spec.nodeName"
  output = ""

[[snippets]]
  description = "kubernetes: kubectl: Start a pod in a specific node"
  command = "kubectl run  --namespace <namespace> --generator=run-pod/v1 -ti --rm test-$RANDOM --image=ecerulm/ubuntu-tools:latest --overrides='{\"spec\": { \"nodeSelector\": {\"nodename\": \"<nodename>\"}}}'"
  output = ""

[[snippets]]
  description = "kubernetes: kubectl: Get the CA.crt"
  command = "kubectl get secret $(kubectl get secret -o json | jq -r '.items[] | .metadata.name | select(startswith(\"default-token\"))') -o jsonpath=\"{['data']['ca\\.crt']}\" | base64 --decode"
  output = ""

[[snippets]]
  description = "kubernetes: kubectl: Get the Kubernetes API URL"
  command = "kubectl config view --minify -o jsonpath=\"{.clusters[0].cluster.server}\""
  output = ""

[[snippets]]
  description = "kubernetes: kubectl: Show all PersistentVolumes and it's EBS volume"
  command = "kubectl get pv -o custom-columns='Name:metadata.name,Claim:.spec.claimRef.name,DATA:spec.awsElasticBlockStore.volumeID'"
  output = ""

[[snippets]]
  description = "kubernetes: kubectl: Restarting all pods on a deployment"
  command = "kubectl -n <namespace> rollout restart deployment/<deploymentname>"
  output = ""

[[snippets]]
  description = "kubernetes: kubectl: Get the all pods in Completed state"
  command = "kubectl -n <namespace=airflow-prod> get pods --field-selector 'status.phase=Succeeded'"
  output = ""

[[snippets]]
  description = "kubernetes: Get a shell into a running Pod / container"
  command = "kubectl -n <namespace> exec -it <podname> -c <containername> -- <command=/bin/sh>"
  output = ""

[[snippets]]
  description = "kubernetes: troubleshooting: get all events in a namespace"
  command = "kubectl -n <namespace> get events --sort-by='{.lastTimestamp}'"
  output = ""

[[snippets]]
  description = "kubernetes:kubectl: get current context"
  command = "kubectl config current-context"
  output = ""

[[snippets]]
  description = "vim: clean: no profile fresh install"
  command = "vim --clean"
  output = ""

[[snippets]]
  description = "EKS: get authentication token"
  command = "aws --profile <AWS_PROFILE> eks get-token --cluster-name <eks_cluster_name> | jq -r '.status.token' | pbcopy"
  output = ""

[[snippets]]
  description = "kubernetes: eks: Update the local kubeconfig with the aws token"
  command = "aws eks --profile <aws_profile> update-kubeconfig --name <eks-cluster-name>"
  output = ""

[[snippets]]
  description = "Remove quarantine from file, solve unidentified developer"
  command = "xattr -d com.apple.quarantine <file>"
  output = ""

[[snippets]]
  description = "git: list all tags / show all tags"
  command = "git fetch --tags && git tag"
  output = ""
